name: 构建 Newapi

on:
  workflow_dispatch:
    inputs:
      tag:
        description: '要构建的标签'
        required: true
        type: string

jobs:
  push_to_registries:
    name: 推送 Docker 镜像到多个注册表
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: 检出仓库
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.tag }}

      - name: 获取所有标签
        run: |
          git fetch --tags

      - name: 调试标签是否存在
        run: |
          git tag -l
          git show-ref --tags

      - name: 保存版本信息
        run: |
          echo ${{ github.event.inputs.tag }} > VERSION 

      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v2

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 登录到 Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 登录到 Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REPO_PAT }}

      - name: 提取 Docker 的元数据（标签、标签）
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            fzx401/new-api
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ github.event.inputs.tag }}
            type=raw,value=latest

      - name: 构建并推送 Docker 镜像
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
