name: 构建 Newapi

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 */6 * * *'  # 每6小时运行一次

jobs:
  push_to_registries:
    name: 推送 Docker 镜像到多个注册表
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: 检出 fzx new-api 仓库
        uses: actions/checkout@v3
        with:
          repository: fengzaixing401/new-api
          token: ${{ secrets.REPO_PAT }}
          fetch-depth: 0

      - name: 获取最新标签
        id: get_latest_tag
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV

      - name: 检出最新标签
        uses: actions/checkout@v3
        with:
          repository: fengzaixing401/new-api
          token: ${{ secrets.REPO_PAT }}
          fetch-depth: 0
          ref: ${{ env.LATEST_TAG }}

      - name: 保存版本信息
        run: |
          echo ${{ env.LATEST_TAG }} > VERSION 

      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v2

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 登录到 Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 登录到 Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REPO_PAT }}

      - name: 提取 Docker 的元数据（标签、标签）
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            fzx401/new-api
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ env.LATEST_TAG }}
            type=raw,value=latest

      - name: 构建并推送 Docker 镜像
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
