name: Check Newapi Update and Build

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    outputs:
      has_updates: ${{ steps.check_updates.outputs.has_updates }}
    steps:
      - name: Checkout Work repository
        uses: actions/checkout@v3
        with:
          repository: fengzaixing401/Work
          token: ${{ secrets.REPO_PAT }}
          fetch-depth: 0  # 获取完整历史记录

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Check for upstream updates
        id: check_updates
        run: |
          git clone --depth=1 https://github.com/fengzaixing401/new-api.git
          cd new-api
          git remote add upstream https://github.com/Calcium-Ion/new-api.git
          git fetch upstream
          if git diff --quiet HEAD upstream/main; then
            echo "No updates found"
            echo "has_updates=false" >> $GITHUB_OUTPUT
          else
            echo "Updates found"
            echo "has_updates=true" >> $GITHUB_OUTPUT
            git merge upstream/main
            git push https://${{ secrets.REPO_PAT }}@github.com/fengzaixing401/new-api.git main
          fi

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

  build:
    needs: check-and-update
    if: needs.check-and-update.outputs.has_updates == 'true'
    uses: ./.github/workflows/Build Newapi.yml
    with:
      branch: 'main'
    secrets: inherit
