name: 检查 Newapi 更新并触发构建

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: 检出 fzx new-api 仓库
        uses: actions/checkout@v3
        with:
          repository: fengzaixing401/new-api
          token: ${{ secrets.REPO_PAT }}
          fetch-depth: 0

      - name: 配置 Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: 检查上游更新并同步
        id: check_updates
        run: |
          git remote add upstream https://github.com/Calcium-Ion/new-api.git
          
          # 拉取原始仓库数据
          git fetch upstream
          
          # 检查是否有新的提交
          if git diff --quiet HEAD upstream/main; then
            echo "代码没有更新"
            HAS_UPDATES=false
          else
            echo "发现更新，正在同步"
            git rebase upstream/main
            git push --force-with-lease
            HAS_UPDATES=true
          fi
          
          # 同步标签
          git fetch --tags upstream
          git push --tags
          
          # 获取最新的标签
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          
          # 设置输出
          echo "has_updates=$HAS_UPDATES" >> $GITHUB_OUTPUT
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: 触发 Build Newapi 工作流
        if: steps.check_updates.outputs.has_updates == 'true'
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.REPO_PAT }}" \
            https://api.github.com/repos/fengzaixing401/work/actions/workflows/Build%20Newapi.yml/dispatches \
            -d '{"ref":"main"}'
