name: 检查 Newapi 更新并触发构建

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: 检出 fzx new-api 仓库
        uses: actions/checkout@v3
        with:
          repository: fengzaixing401/new-api
          token: ${{ secrets.REPO_PAT }}
          fetch-depth: 0

      - name: 配置 Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: 检查上游更新并同步
        id: check_updates
        run: |
          git remote add upstream https://github.com/Calcium-Ion/new-api.git
          git fetch upstream
          LATEST_TAG=$(git ls-remote --tags --refs upstream | sort -V | tail -n 1 | sed 's/.*\///')
          if git diff --quiet HEAD upstream/main; then
            echo "未发现更新"
            echo "has_updates=false" >> $GITHUB_OUTPUT
          else
            echo "发现更新，正在同步"
            git merge upstream/main
            git push
            echo "has_updates=true" >> $GITHUB_OUTPUT
          fi
          echo "latest_tag=${LATEST_TAG}" >> $GITHUB_OUTPUT

      - name: 同步上游标签
        if: steps.check_updates.outputs.has_updates == 'true'
        run: |
          git fetch upstream --tags
          git tag ${{ steps.check_updates.outputs.latest_tag }} upstream/${{ steps.check_updates.outputs.latest_tag }}
          git push origin ${{ steps.check_updates.outputs.latest_tag }}

      - name: 触发 Build Newapi 工作流
        if: steps.check_updates.outputs.has_updates == 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Build Newapi.yml
          token: ${{ secrets.REPO_PAT }}
          inputs: '{"tag": "${{ steps.check_updates.outputs.latest_tag }}"}'
